<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_00</name>
   <tag></tag>
   <elementGuidId>6a3b5996-aed3-43e3-bc53-cd8fffd29f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-vfb-16-hour-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-vfb-16-hour-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0af3054d-bf29-4a8f-8f3c-33fb978788fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>50de69c7-cddd-41de-a99d-b4aaf718c855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vfb-16-hour-container</value>
      <webElementGuid>8b393e60-ce22-4d37-9be4-9336f1ebae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0d1235d0-5db1-478c-a663-a88665b1f7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>141c91a8-d868-42b0-be82-aff18c5767c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>c30e9cae-ca2a-4b96-8e72-4deafb8a17e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>d26f4eb6-6b9d-4b82-987c-79f2f70b77fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vfb-16-hour-container&quot;)</value>
      <webElementGuid>e7d84adb-8278-41a6-9bc0-8fdecfe87097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vfb-16-hour-container']</value>
      <webElementGuid>ef923cc0-b380-4197-84d5-3c1ff508c216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-16']/span/span/span/span/span</value>
      <webElementGuid>eff98cfd-50af-4c9f-8866-f3472057f6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenient Time'])[1]/following::span[5]</value>
      <webElementGuid>8b56eaf4-60b8-4809-bb1f-caf15d17e226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter in MM/DD/YY Format'])[1]/following::span[5]</value>
      <webElementGuid>6939e0af-e5e4-4a3b-af16-f72a9f197b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HH'])[1]/preceding::span[3]</value>
      <webElementGuid>da11d570-22de-4393-badc-d77fa75d4e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM'])[1]/preceding::span[9]</value>
      <webElementGuid>d60c9d33-54eb-49bb-a506-2c18ed224685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span/span/span/span/span</value>
      <webElementGuid>68338fda-c25a-4d53-8e85-8a0af1c9e84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vfb-16-hour-container' and @title = '00' and (text() = '00' or . = '00')]</value>
      <webElementGuid>535eef8b-4c50-43d2-968a-c7a3614d6c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
